apiVersion: v1
kind: Service
metadata:
  name: test1
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: test2
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 7776
      targetPort: 7776
  type: NodePort
